### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by englercj** [CloudKidStudio/PixiParticles#13]
This looks really cool!

You should publish it on npm (probably as `pixi-particles`), and add it to the plugin list on our Wiki: https://github.com/pixijs/pixi.js/wiki/Pixi-v3-Plugins

Let me know if you need help setting up the npm stuff, don't mind making a PR for it.

**Comment by AMorporkian** [comment]
+1 on this. I use this actively on one of my projects, and 

    import "../../lib/pixi-particles/pixi-particles.js"

Is a lot uglier than

    import "pixi-particles"

**Comment by bigtimebuddy** [comment]
@englercj Chad, feel free to make a PR for the NPM integration, we'd be happy to add it.

**Comment by Oza94** [comment]
Hi @bigtimebuddy please see #15 , the only thing to do after merging is:

```
npm adduser #if not already done
npm publish .
```

In the project directory. Don't forget to do it for each release, npm doesn't rely on github tags like bower! 

For those interested, I have published a temporary package on npm (with relevant warning notices about the fact I'm not the author): https://www.npmjs.com/package/pixi-particles-temporary

It's already marked deprecated because as soon as you publish yours, I unpublish mine.

**Comment by bigtimebuddy** [comment]
Okay `pixi-particles

**Comment by Oza94** [comment]
Unpublished `pixi-particles-temporary`, it was a falling star! Thanks for your reactivity

**Comment by bigtimebuddy** [comment]
@englercj Please feel free to add pixi-particles to the list Pixi.js wiki plugin links.

**Comment by englercj** [comment]
Added:
https://github.com/pixijs/pixi.js/wiki/Pixi-v3-Plugins

Sorry I didn't get around to that PR, been out of town for the past week or so.
