### ISSUE TITLE
Acceleration should be cloned not referenced

### ISSUE THREAD

**Issue by joeredfearn** [CloudKidStudio/PixiParticles#17]
When a particles acceleration is set, it would be handy if you didn't just reference the emitters acceleration but rather you used **.clone()** or set the **x** and **y**. This would allow some behaviours that give particles unique acceleration values.

Let me know what you think!

**Comment by andrewstart** [comment]
I am trying to avoid creating new objects each time I initialize a particle, because there are potentially a lot of particles getting initialized often.
That said, you could certainly make a Particle subclass that does clone the acceleration, and even takes care of the randomization itself. Let me know if the process of making and using a subclass isn't clear enough, I'll whip up a tutorial or example on it.

**Comment by joeredfearn** [comment]
You are correct **.clone()** would be the wrong thing to do but surely

```javascript
p.acceleration.x = this.acceleration.x;
p.acceleration.y = this.acceleration.y;
```

should be enough?

**Comment by andrewstart** [comment]
That would be fine, although then I would set **_doNormalMovement** and make **_doAcceleration** on the particle to false if the acceleration is 0, so you would want to set those to true if you wanted the acceleration to start at 0 and then change it later..

**Comment by andrewstart** [comment]
Closing this, because I did make acceleration a thing that is copied instead of a reference to the original point.
